updates:
  # Enable version updates for GitHub Actions
  - cooldown:
      default-days: 7
    # Look for workflow files in the `.github/workflows` directory
    directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
  # Enable version updates for npm
  - cooldown:
      default-days: 7
    # Look for `package.json` and lock files in the root directory
    directory: /
    package-ecosystem: npm
    schedule:
      interval: weekly
version: 2
