packages:
  - "."

catalog:
  "@eslint-community/eslint-plugin-eslint-comments": 4.5.0
  "@eslint/js": 9.39.1
  "@release-it/conventional-changelog": 10.0.1
  "@types/eslint-plugin-markdown": 2.0.2
  "@types/node": 24.10.1
  "@vitest/coverage-v8": 3.2.4
  "@vitest/eslint-plugin": 1.2.7
  console-fail-test: 0.5.0
  cspell: 9.1.2
  eslint: 9.39.1
  eslint-plugin-jsdoc: 52.0.0
  eslint-plugin-jsonc: 2.20.1
  eslint-plugin-markdown: 5.1.0
  eslint-plugin-n: 17.21.0
  eslint-plugin-package-json: 0.48.0
  eslint-plugin-perfectionist: 4.15.0
  eslint-plugin-pnpm: ^1.3.0
  eslint-plugin-regexp: 2.9.0
  eslint-plugin-yml: 1.18.0
  husky: 9.1.7
  knip: 5.61.2
  lint-staged: 16.1.2
  markdownlint: 0.38.0
  markdownlint-cli: 0.45.0
  prettier: 3.6.1
  prettier-plugin-curly: 0.3.2
  prettier-plugin-packagejson: 2.5.15
  prettier-plugin-sh: 0.17.4
  release-it: 19.0.3
  sentences-per-line: 0.3.0
  tsdown: 0.12.7
  typescript: 5.9.2
  typescript-eslint: 8.46.0
  vitest: 3.2.4
