catalog:
  "@eslint-community/eslint-plugin-eslint-comments": 4.6.0
  "@eslint/js": 9.34.0
  "@release-it/conventional-changelog": ^10.0.4
  "@types/eslint-plugin-markdown": 2.0.2
  "@types/node": 25.0.3
  "@vitest/coverage-v8": 3.2.4
  "@vitest/eslint-plugin": 1.2.7
  console-fail-test: 0.6.1
  cspell: 9.1.2
  eslint: 9.39.2
  eslint-doc-generator: ^2.4.0
  eslint-plugin-dependabot: ^0.4.0
  eslint-plugin-eslint-plugin: ^7.2.0
  eslint-plugin-jsdoc: 62.4.0
  eslint-plugin-jsonc: 2.20.1
  eslint-plugin-markdown: 5.1.0
  eslint-plugin-n: 17.21.0
  eslint-plugin-package-json: 0.88.1
  eslint-plugin-perfectionist: 4.15.0
  eslint-plugin-pnpm: ^1.4.3
  eslint-plugin-regexp: 2.10.0
  eslint-plugin-yml: 1.18.0
  eslint-yaml: 0.1.0
  knip: 5.72.0
  lefthook: 1.10.3
  markdownlint: 0.38.0
  markdownlint-cli: 0.47.0
  pkg-pr-new: ^0.0.60
  prettier: 3.6.1
  prettier-plugin-curly: 0.3.2
  prettier-plugin-packagejson: 3.0.0
  prettier-plugin-sh: 0.17.4
  release-it: ^19.2.2
  sentences-per-line: 0.3.0
  should-semantic-release: ^0.3.5
  tsdown: 0.12.7
  typescript: 5.9.2
  typescript-eslint: 8.53.1
  vitest: 3.2.4
  yaml: 2.8.0

minimumReleaseAge: 10080

packages:
  - .
